// Type: System.Reactive.EventPattern`1
// Assembly: System.Reactive.Linq, Version=2.0.20823.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// Assembly location: D:\Users\G90082C\Documents\GitHub\PatternsAndPractices\Data\Querying\packages\Rx-Linq.2.0.21114\lib\Net40\System.Reactive.Linq.dll

using System;

namespace System.Reactive
{
	/// <summary>
	/// Represents a .NET event invocation consisting of the weakly typed object that raised the event and the data that was generated by the event.
	/// 
	/// </summary>
	/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
	public class EventPattern<TEventArgs> : EventPattern<object, TEventArgs> where TEventArgs : EventArgs
	{
		/// <summary>
		/// Creates a new data representation instance of a .NET event invocation with the given sender and event data.
		/// 
		/// </summary>
		/// <param name="sender">The sender object that raised the event.</param><param name="e">The event data that was generated by the event.</param>
		public EventPattern(object sender, TEventArgs e);
	}
}
